apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  # Non-sensitive configuration goes here
  USER_DB_URL: "mongodb://mongo-user:27017/userdb"
  ORDER_DB_URL: "mongodb://mongo-order:27017/orderdb"
---
apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
type: Opaque
stringData: 
  # Sensitive data goes here! 
  # (Note: K8s encrypts Secrets in its internal database. We use 'stringData' 
  # so we don't have to manually base64 encode the values before typing them here).
  JWT_SECRET_KEY: "my-super-secret-production-key-123"